services:

  mongo:
    image: mongo
    container_name: cafe-trade.db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${DB_NAME}
    ports:
      - 27027:27017
    volumes:
      - ./db:/data/db
    networks:
      - cafe-trade-network-dev

  mongo-express:
    image: mongo-express
    container_name: cafe-trade.db-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGOEXPRESS_LOGIN}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGOEXPRESS_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017
    depends_on:
      - mongo
    networks:
      - cafe-trade-network-dev

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: cafe-trade.server
    restart: always
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
    networks:
      - cafe-trade-network-dev

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: cafe-trade.client
    restart: always
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 5173:5173
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
    networks:
      - cafe-trade-network-dev

  nginx:
    image: nginx:alpine
    container_name: cafe-trade.nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/dev.conf:/etc/nginx/nginx.conf
    depends_on:
      - server
      - client
    networks:
      - cafe-trade-network-dev

networks:
  cafe-trade-network-dev:
    driver: bridge